version: "3.3"
services:
  apache:
    container_name: apache
    build: ./frontend/apache_server
    links:
      - php
    ports:
      - "8084:80"
    volumes:
      - ./src:/usr/local/apache2/htdocs
  php:
    container_name: php
    build: ./frontend/php_server
    links:
      - mysql
    ports:
      - "9000:9000"
    volumes:
      - ./src:/usr/local/apache2/htdocs
    working_dir: /usr/local/apache2/htdocs
  mysql:
    image: mysql:8.0.27
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: webDB
      MYSQL_USER: studentin
      MYSQL_PASSWORD: ''
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8085:80

